# ---
# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: demo
# spec:
#   domains:
#   - nextjs.nodematic.io
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: demo-admin
# spec:
#   redirectToHttps:
#     enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-admin
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: demo-admin
    networking.gke.io/v1beta1.FrontendConfig: demo-admin
    networking.gke.io/managed-certificates: demo-admin
spec:
  defaultBackend:
    service:
      name: demo-admin
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-admin
spec:
  type: LoadBalancer
  selector:
    app: demo-admin
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-admin
  labels:
    app: demo-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-admin
  template:
    metadata:
      labels:
        app: demo-admin
    spec:
      containers:
      - name: demo-admin
        image: asia-southeast1-docker.pkg.dev/zinc-presence-444907-g3/demo-admin/app:latest